sudo: required
services:
    - docker

before_install:
    - docker build -t ayanezsouto/react-test -f Dockerfile.dev ./client
    
script:
    - docker run -e CI=true ayanezsouto/react-test npm run test
    
after_success:
    - docker build -t ayanezsouto/multi-client ./client
    - docker build -t ayanezsouto/multi-nginx ./nginx
    - docker build -t ayanezsouto/multi-server ./server
    - docker build -t ayanezsouto/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stind
    # Take those images and push them to Docker Hub
    - docker push ayanezsouto/multi-client
    - docker push ayanezsouto/multi-nginx
    - docker push ayanezsouto/multi-server
    - docker push ayanezsouto/multi-worker